-- Database Optimization Migration
-- Run this after applying the suite schema
-- Generated by database-designer skill

-- ============================================
-- ADDITIONAL INDEXES FOR PERFORMANCE
-- ============================================

-- Composite indexes for common queries
CREATE INDEX IF NOT EXISTS idx_releases_artist_date ON public.releases(artist_id, release_date DESC);
CREATE INDEX IF NOT EXISTS idx_tracks_plays ON public.tracks(plays DESC) WHERE plays > 0;
CREATE INDEX IF NOT EXISTS idx_projects_status_date ON public.projects(status, target_release_date);
CREATE INDEX IF NOT EXISTS idx_tasks_priority_due ON public.tasks(priority, due_date) WHERE status != 'completed';

-- Indexes for media queries
CREATE INDEX IF NOT EXISTS idx_media_assets_type ON public.media_assets(file_type, asset_type);
CREATE INDEX IF NOT EXISTS idx_media_assets_latest ON public.media_assets(is_latest_version) WHERE is_latest_version = true;

-- Indexes for AI features
CREATE INDEX IF NOT EXISTS idx_ai_plans_project ON public.ai_plans(project_id, status);
CREATE INDEX IF NOT EXISTS idx_ai_executions_status ON public.ai_executions(status, started_at DESC);

-- ============================================
-- ENABLE PG_TRGM FOR TEXT SEARCH (if not exists)
-- ============================================
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Full-text search indexes
CREATE INDEX IF NOT EXISTS idx_artists_name_trgm ON public.artists USING gin(name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_releases_title_trgm ON public.releases USING gin(title gin_trgm_ops);

-- ============================================
-- JSONB INDEXES FOR AI DATA
-- ============================================
CREATE INDEX IF NOT EXISTS idx_ai_plans_data ON public.ai_plans USING gin(plan_data);
CREATE INDEX IF NOT EXISTS idx_ai_executions_actions ON public.ai_executions USING gin(actions_taken);

-- ============================================
-- MATERIALIZED VIEW FOR ANALYTICS
-- ============================================
CREATE MATERIALIZED VIEW IF NOT EXISTS public.artist_stats AS
SELECT
    a.id,
    a.name,
    a.slug,
    COUNT(DISTINCT r.id) as release_count,
    COUNT(DISTINCT t.id) as track_count,
    COALESCE(SUM(t.plays), 0) as total_plays,
    MAX(r.release_date) as latest_release_date
FROM public.artists a
LEFT JOIN public.releases r ON r.artist_id = a.id
LEFT JOIN public.tracks t ON t.artist_id = a.id
GROUP BY a.id, a.name, a.slug;

CREATE UNIQUE INDEX IF NOT EXISTS idx_artist_stats_id ON public.artist_stats(id);

-- ============================================
-- FUNCTION TO REFRESH MATERIALIZED VIEW
-- ============================================
CREATE OR REPLACE FUNCTION public.refresh_artist_stats()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY public.artist_stats;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- API RATE LIMITING TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.api_rate_limits (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    endpoint text NOT NULL,
    requests_count integer DEFAULT 1,
    window_start timestamp with time zone DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, endpoint, window_start)
);

CREATE INDEX IF NOT EXISTS idx_rate_limits_user_endpoint ON public.api_rate_limits(user_id, endpoint, window_start);
CREATE INDEX IF NOT EXISTS idx_rate_limits_window ON public.api_rate_limits(window_start);

-- ============================================
-- ADD RLS POLICY FOR API RATE LIMITS
-- ============================================
ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own rate limits" ON public.api_rate_limits
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- SEARCH HELPER FUNCTION
-- ============================================
CREATE OR REPLACE FUNCTION public.search_artists(search_term text)
RETURNS TABLE (
    id uuid,
    name text,
    slug text,
    similarity real
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        a.id,
        a.name,
        a.slug,
        similarity(a.name, search_term) as sim
    FROM public.artists a
    WHERE a.name % search_term
    ORDER BY sim DESC
    LIMIT 20;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.search_artists IS 'Search artists using trigram similarity';
